# Country data with flags, phone codes, verification codes, and languages
COUNTRIES_DATA = {
    'US': {'name': 'United States', 'flag': '🇺🇸', 'code': '+1', 'verification': '111111', 'language': 'en'},
    'CA': {'name': 'Canada', 'flag': '🇨🇦', 'code': '+1', 'verification': '111111', 'language': 'en'},
    'GB': {'name': 'United Kingdom', 'flag': '🇬🇧', 'code': '+44', 'verification': '111111', 'language': 'en'},
    'AU': {'name': 'Australia', 'flag': '🇦🇺', 'code': '+61', 'verification': '111111', 'language': 'en'},
    'DE': {'name': 'Germany', 'flag': '🇩🇪', 'code': '+49', 'verification': '111111', 'language': 'de'},
    'FR': {'name': 'France', 'flag': '🇫🇷', 'code': '+33', 'verification': '111111', 'language': 'fr'},
    'ES': {'name': 'Spain', 'flag': '🇪🇸', 'code': '+34', 'verification': '111111', 'language': 'es'},
    'IT': {'name': 'Italy', 'flag': '🇮🇹', 'code': '+39', 'verification': '111111', 'language': 'it'},
    'JP': {'name': 'Japan', 'flag': '🇯🇵', 'code': '+81', 'verification': '111111', 'language': 'ja'},
    'BR': {'name': 'Brazil', 'flag': '🇧🇷', 'code': '+55', 'verification': '111111', 'language': 'pt'},
    'MX': {'name': 'Mexico', 'flag': '🇲🇽', 'code': '+52', 'verification': '111111', 'language': 'es'},
    'IN': {'name': 'India', 'flag': '🇮🇳', 'code': '+91', 'verification': '111111', 'language': 'en'},
    'CN': {'name': 'China', 'flag': '🇨🇳', 'code': '+86', 'verification': '111111', 'language': 'zh'},
    'NG': {'name': 'Nigeria', 'flag': '🇳🇬', 'code': '+234', 'verification': '222222', 'language': 'en'},
    'ZA': {'name': 'South Africa', 'flag': '🇿🇦', 'code': '+27', 'verification': '222222', 'language': 'en'},
    'EG': {'name': 'Egypt', 'flag': '🇪🇬', 'code': '+20', 'verification': '222222', 'language': 'ar'},
    'KE': {'name': 'Kenya', 'flag': '🇰🇪', 'code': '+254', 'verification': '222222', 'language': 'en'},
    'GH': {'name': 'Ghana', 'flag': '🇬🇭', 'code': '+233', 'verification': '222222', 'language': 'en'},
    'MA': {'name': 'Morocco', 'flag': '🇲🇦', 'code': '+212', 'verification': '222222', 'language': 'ar'},
    'TN': {'name': 'Tunisia', 'flag': '🇹🇳', 'code': '+216', 'verification': '222222', 'language': 'ar'},
    'DZ': {'name': 'Algeria', 'flag': '🇩🇿', 'code': '+213', 'verification': '222222', 'language': 'ar'},
    'LY': {'name': 'Libya', 'flag': '🇱🇾', 'code': '+218', 'verification': '222222', 'language': 'ar'},
    'SD': {'name': 'Sudan', 'flag': '🇸🇩', 'code': '+249', 'verification': '222222', 'language': 'ar'},
    'ET': {'name': 'Ethiopia', 'flag': '🇪🇹', 'code': '+251', 'verification': '222222', 'language': 'en'},
    'UG': {'name': 'Uganda', 'flag': '🇺🇬', 'code': '+256', 'verification': '222222', 'language': 'en'},
    'TZ': {'name': 'Tanzania', 'flag': '🇹🇿', 'code': '+255', 'verification': '222222', 'language': 'en'},
    'RW': {'name': 'Rwanda', 'flag': '🇷🇼', 'code': '+250', 'verification': '222222', 'language': 'en'},
    'ZM': {'name': 'Zambia', 'flag': '🇿🇲', 'code': '+260', 'verification': '222222', 'language': 'en'},
    'ZW': {'name': 'Zimbabwe', 'flag': '🇿🇼', 'code': '+263', 'verification': '222222', 'language': 'en'},
    'BW': {'name': 'Botswana', 'flag': '🇧🇼', 'code': '+267', 'verification': '222222', 'language': 'en'},
    'NA': {'name': 'Namibia', 'flag': '🇳🇦', 'code': '+264', 'verification': '222222', 'language': 'en'},
    'MW': {'name': 'Malawi', 'flag': '🇲🇼', 'code': '+265', 'verification': '222222', 'language': 'en'},
    'SZ': {'name': 'Eswatini', 'flag': '🇸🇿', 'code': '+268', 'verification': '222222', 'language': 'en'},
    'LS': {'name': 'Lesotho', 'flag': '🇱🇸', 'code': '+266', 'verification': '222222', 'language': 'en'},
    'MG': {'name': 'Madagascar', 'flag': '🇲🇬', 'code': '+261', 'verification': '222222', 'language': 'fr'},
    'MU': {'name': 'Mauritius', 'flag': '🇲🇺', 'code': '+230', 'verification': '222222', 'language': 'en'},
    'SC': {'name': 'Seychelles', 'flag': '🇸🇨', 'code': '+248', 'verification': '222222', 'language': 'en'},
    'KM': {'name': 'Comoros', 'flag': '🇰🇲', 'code': '+269', 'verification': '222222', 'language': 'fr'},
    'DJ': {'name': 'Djibouti', 'flag': '🇩🇯', 'code': '+253', 'verification': '222222', 'language': 'fr'},
    'SO': {'name': 'Somalia', 'flag': '🇸🇴', 'code': '+252', 'verification': '222222', 'language': 'so'},
    'ER': {'name': 'Eritrea', 'flag': '🇪🇷', 'code': '+291', 'verification': '222222', 'language': 'en'},
    'SS': {'name': 'South Sudan', 'flag': '🇸🇸', 'code': '+211', 'verification': '222222', 'language': 'en'},
    'CF': {'name': 'Central African Republic', 'flag': '🇨🇫', 'code': '+236', 'verification': '222222', 'language': 'fr'},
    'TD': {'name': 'Chad', 'flag': '🇹🇩', 'code': '+235', 'verification': '222222', 'language': 'fr'},
    'CM': {'name': 'Cameroon', 'flag': '🇨🇲', 'code': '+237', 'verification': '222222', 'language': 'fr'},
    'NE': {'name': 'Niger', 'flag': '🇳🇪', 'code': '+227', 'verification': '222222', 'language': 'fr'},
    'BF': {'name': 'Burkina Faso', 'flag': '🇧🇫', 'code': '+226', 'verification': '222222', 'language': 'fr'},
    'ML': {'name': 'Mali', 'flag': '🇲🇱', 'code': '+223', 'verification': '222222', 'language': 'fr'},
    'SN': {'name': 'Senegal', 'flag': '🇸🇳', 'code': '+221', 'verification': '222222', 'language': 'fr'},
    'GM': {'name': 'Gambia', 'flag': '🇬🇲', 'code': '+220', 'verification': '222222', 'language': 'en'},
    'GN': {'name': 'Guinea', 'flag': '🇬🇳', 'code': '+224', 'verification': '222222', 'language': 'fr'},
    'GW': {'name': 'Guinea-Bissau', 'flag': '🇬🇼', 'code': '+245', 'verification': '222222', 'language': 'pt'},
    'LR': {'name': 'Liberia', 'flag': '🇱🇷', 'code': '+231', 'verification': '222222', 'language': 'en'},
    'SL': {'name': 'Sierra Leone', 'flag': '🇸🇱', 'code': '+232', 'verification': '222222', 'language': 'en'},
    'CI': {'name': 'Côte d\'Ivoire', 'flag': '🇨🇮', 'code': '+225', 'verification': '222222', 'language': 'fr'},
    'TG': {'name': 'Togo', 'flag': '🇹🇬', 'code': '+228', 'verification': '222222', 'language': 'fr'},
    'BJ': {'name': 'Benin', 'flag': '🇧🇯', 'code': '+229', 'verification': '222222', 'language': 'fr'},
    'AO': {'name': 'Angola', 'flag': '🇦🇴', 'code': '+244', 'verification': '222222', 'language': 'pt'},
    'MZ': {'name': 'Mozambique', 'flag': '🇲🇿', 'code': '+258', 'verification': '222222', 'language': 'pt'},
    'CV': {'name': 'Cape Verde', 'flag': '🇨🇻', 'code': '+238', 'verification': '222222', 'language': 'pt'},
    'ST': {'name': 'São Tomé and Príncipe', 'flag': '🇸🇹', 'code': '+239', 'verification': '222222', 'language': 'pt'},
    'GQ': {'name': 'Equatorial Guinea', 'flag': '🇬🇶', 'code': '+240', 'verification': '222222', 'language': 'es'},
    'GA': {'name': 'Gabon', 'flag': '🇬🇦', 'code': '+241', 'verification': '222222', 'language': 'fr'},
    'CG': {'name': 'Republic of the Congo', 'flag': '🇨🇬', 'code': '+242', 'verification': '222222', 'language': 'fr'},
    'CD': {'name': 'Democratic Republic of the Congo', 'flag': '🇨🇩', 'code': '+243', 'verification': '222222', 'language': 'fr'},
    'BI': {'name': 'Burundi', 'flag': '🇧🇮', 'code': '+257', 'verification': '222222', 'language': 'fr'},
    'YT': {'name': 'Mayotte', 'flag': '🇾🇹', 'code': '+262', 'verification': '222222', 'language': 'fr'},
    'RE': {'name': 'Réunion', 'flag': '🇷🇪', 'code': '+262', 'verification': '222222', 'language': 'fr'},
    'AR': {'name': 'Argentina', 'flag': '🇦🇷', 'code': '+54', 'verification': '111111', 'language': 'es'},
    'CL': {'name': 'Chile', 'flag': '🇨🇱', 'code': '+56', 'verification': '111111', 'language': 'es'},
    'CO': {'name': 'Colombia', 'flag': '🇨🇴', 'code': '+57', 'verification': '111111', 'language': 'es'},
    'PE': {'name': 'Peru', 'flag': '🇵🇪', 'code': '+51', 'verification': '111111', 'language': 'es'},
    'VE': {'name': 'Venezuela', 'flag': '🇻🇪', 'code': '+58', 'verification': '111111', 'language': 'es'},
    'EC': {'name': 'Ecuador', 'flag': '🇪🇨', 'code': '+593', 'verification': '111111', 'language': 'es'},
    'BO': {'name': 'Bolivia', 'flag': '🇧🇴', 'code': '+591', 'verification': '111111', 'language': 'es'},
    'PY': {'name': 'Paraguay', 'flag': '🇵🇾', 'code': '+595', 'verification': '111111', 'language': 'es'},
    'UY': {'name': 'Uruguay', 'flag': '🇺🇾', 'code': '+598', 'verification': '111111', 'language': 'es'},
    'GY': {'name': 'Guyana', 'flag': '🇬🇾', 'code': '+592', 'verification': '111111', 'language': 'en'},
    'SR': {'name': 'Suriname', 'flag': '🇸🇷', 'code': '+597', 'verification': '111111', 'language': 'nl'},
    'FK': {'name': 'Falkland Islands', 'flag': '🇫🇰', 'code': '+500', 'verification': '111111', 'language': 'en'},
    'RU': {'name': 'Russia', 'flag': '🇷🇺', 'code': '+7', 'verification': '111111', 'language': 'ru'},
    'KZ': {'name': 'Kazakhstan', 'flag': '🇰🇿', 'code': '+7', 'verification': '111111', 'language': 'ru'},
    'UZ': {'name': 'Uzbekistan', 'flag': '🇺🇿', 'code': '+998', 'verification': '111111', 'language': 'uz'},
    'KG': {'name': 'Kyrgyzstan', 'flag': '🇰🇬', 'code': '+996', 'verification': '111111', 'language': 'ky'},
    'TJ': {'name': 'Tajikistan', 'flag': '🇹🇯', 'code': '+992', 'verification': '111111', 'language': 'tg'},
    'TM': {'name': 'Turkmenistan', 'flag': '🇹🇲', 'code': '+993', 'verification': '111111', 'language': 'tk'},
    'AF': {'name': 'Afghanistan', 'flag': '🇦🇫', 'code': '+93', 'verification': '111111', 'language': 'fa'},
    'PK': {'name': 'Pakistan', 'flag': '🇵🇰', 'code': '+92', 'verification': '111111', 'language': 'ur'},
    'BD': {'name': 'Bangladesh', 'flag': '🇧🇩', 'code': '+880', 'verification': '111111', 'language': 'bn'},
    'LK': {'name': 'Sri Lanka', 'flag': '🇱🇰', 'code': '+94', 'verification': '111111', 'language': 'si'},
    'MV': {'name': 'Maldives', 'flag': '🇲🇻', 'code': '+960', 'verification': '111111', 'language': 'dv'},
    'BT': {'name': 'Bhutan', 'flag': '🇧🇹', 'code': '+975', 'verification': '111111', 'language': 'dz'},
    'NP': {'name': 'Nepal', 'flag': '🇳🇵', 'code': '+977', 'verification': '111111', 'language': 'ne'},
    'MM': {'name': 'Myanmar', 'flag': '🇲🇲', 'code': '+95', 'verification': '111111', 'language': 'my'},
    'TH': {'name': 'Thailand', 'flag': '🇹🇭', 'code': '+66', 'verification': '111111', 'language': 'th'},
    'LA': {'name': 'Laos', 'flag': '🇱🇦', 'code': '+856', 'verification': '111111', 'language': 'lo'},
    'KH': {'name': 'Cambodia', 'flag': '🇰🇭', 'code': '+855', 'verification': '111111', 'language': 'km'},
    'VN': {'name': 'Vietnam', 'flag': '🇻🇳', 'code': '+84', 'verification': '111111', 'language': 'vi'},
    'MY': {'name': 'Malaysia', 'flag': '🇲🇾', 'code': '+60', 'verification': '111111', 'language': 'ms'},
    'SG': {'name': 'Singapore', 'flag': '🇸🇬', 'code': '+65', 'verification': '111111', 'language': 'en'},
    'BN': {'name': 'Brunei', 'flag': '🇧🇳', 'code': '+673', 'verification': '111111', 'language': 'ms'},
    'ID': {'name': 'Indonesia', 'flag': '🇮🇩', 'code': '+62', 'verification': '111111', 'language': 'id'},
    'PH': {'name': 'Philippines', 'flag': '🇵🇭', 'code': '+63', 'verification': '111111', 'language': 'en'},
    'TW': {'name': 'Taiwan', 'flag': '🇹🇼', 'code': '+886', 'verification': '111111', 'language': 'zh'},
    'HK': {'name': 'Hong Kong', 'flag': '🇭🇰', 'code': '+852', 'verification': '111111', 'language': 'zh'},
    'MO': {'name': 'Macau', 'flag': '🇲🇴', 'code': '+853', 'verification': '111111', 'language': 'zh'},
    'KR': {'name': 'South Korea', 'flag': '🇰🇷', 'code': '+82', 'verification': '111111'},
    'KP': {'name': 'North Korea', 'flag': '🇰🇵', 'code': '+850', 'verification': '111111'},
    'MN': {'name': 'Mongolia', 'flag': '🇲🇳', 'code': '+976', 'verification': '111111'},
    'NL': {'name': 'Netherlands', 'flag': '🇳🇱', 'code': '+31', 'verification': '111111'},
    'BE': {'name': 'Belgium', 'flag': '🇧🇪', 'code': '+32', 'verification': '111111'},
    'LU': {'name': 'Luxembourg', 'flag': '🇱🇺', 'code': '+352', 'verification': '111111'},
    'CH': {'name': 'Switzerland', 'flag': '🇨🇭', 'code': '+41', 'verification': '111111'},
    'AT': {'name': 'Austria', 'flag': '🇦🇹', 'code': '+43', 'verification': '111111'},
    'SE': {'name': 'Sweden', 'flag': '🇸🇪', 'code': '+46', 'verification': '111111'},
    'NO': {'name': 'Norway', 'flag': '🇳🇴', 'code': '+47', 'verification': '111111'},
    'DK': {'name': 'Denmark', 'flag': '🇩🇰', 'code': '+45', 'verification': '111111'},
    'FI': {'name': 'Finland', 'flag': '🇫🇮', 'code': '+358', 'verification': '111111'},
    'IS': {'name': 'Iceland', 'flag': '🇮🇸', 'code': '+354', 'verification': '111111'},
    'IE': {'name': 'Ireland', 'flag': '🇮🇪', 'code': '+353', 'verification': '111111'},
    'PT': {'name': 'Portugal', 'flag': '🇵🇹', 'code': '+351', 'verification': '111111'},
    'GR': {'name': 'Greece', 'flag': '🇬🇷', 'code': '+30', 'verification': '111111'},
    'CY': {'name': 'Cyprus', 'flag': '🇨🇾', 'code': '+357', 'verification': '111111'},
    'MT': {'name': 'Malta', 'flag': '🇲🇹', 'code': '+356', 'verification': '111111'},
    'PL': {'name': 'Poland', 'flag': '🇵🇱', 'code': '+48', 'verification': '111111'},
    'CZ': {'name': 'Czech Republic', 'flag': '🇨🇿', 'code': '+420', 'verification': '111111'},
    'SK': {'name': 'Slovakia', 'flag': '🇸🇰', 'code': '+421', 'verification': '111111'},
    'HU': {'name': 'Hungary', 'flag': '🇭🇺', 'code': '+36', 'verification': '111111'},
    'RO': {'name': 'Romania', 'flag': '🇷🇴', 'code': '+40', 'verification': '111111'},
    'BG': {'name': 'Bulgaria', 'flag': '🇧🇬', 'code': '+359', 'verification': '111111'},
    'HR': {'name': 'Croatia', 'flag': '🇭🇷', 'code': '+385', 'verification': '111111'},
    'SI': {'name': 'Slovenia', 'flag': '🇸🇮', 'code': '+386', 'verification': '111111'},
    'EE': {'name': 'Estonia', 'flag': '🇪🇪', 'code': '+372', 'verification': '111111'},
    'LV': {'name': 'Latvia', 'flag': '🇱🇻', 'code': '+371', 'verification': '111111'},
    'LT': {'name': 'Lithuania', 'flag': '🇱🇹', 'code': '+370', 'verification': '111111'},
    'TR': {'name': 'Turkey', 'flag': '🇹🇷', 'code': '+90', 'verification': '111111'},
    'IL': {'name': 'Israel', 'flag': '🇮🇱', 'code': '+972', 'verification': '111111'},
    'SA': {'name': 'Saudi Arabia', 'flag': '🇸🇦', 'code': '+966', 'verification': '111111'},
    'AE': {'name': 'United Arab Emirates', 'flag': '🇦🇪', 'code': '+971', 'verification': '111111'},
    'QA': {'name': 'Qatar', 'flag': '🇶🇦', 'code': '+974', 'verification': '111111'},
    'KW': {'name': 'Kuwait', 'flag': '🇰🇼', 'code': '+965', 'verification': '111111'},
    'BH': {'name': 'Bahrain', 'flag': '🇧🇭', 'code': '+973', 'verification': '111111'},
    'OM': {'name': 'Oman', 'flag': '🇴🇲', 'code': '+968', 'verification': '111111'},
    'YE': {'name': 'Yemen', 'flag': '🇾🇪', 'code': '+967', 'verification': '111111'},
    'IQ': {'name': 'Iraq', 'flag': '🇮🇶', 'code': '+964', 'verification': '111111'},
    'IR': {'name': 'Iran', 'flag': '🇮🇷', 'code': '+98', 'verification': '111111'},
    'JO': {'name': 'Jordan', 'flag': '🇯🇴', 'code': '+962', 'verification': '111111'},
    'LB': {'name': 'Lebanon', 'flag': '🇱🇧', 'code': '+961', 'verification': '111111'},
    'SY': {'name': 'Syria', 'flag': '🇸🇾', 'code': '+963', 'verification': '111111'},
}

# Language mapping based on country
COUNTRY_LANGUAGES = {
    'US': 'en', 'CA': 'en', 'GB': 'en', 'AU': 'en', 'IN': 'en', 'SG': 'en', 'MY': 'en', 'PH': 'en',
    'DE': 'de', 'AT': 'de', 'CH': 'de',
    'FR': 'fr', 'BE': 'fr', 'CH': 'fr', 'CA': 'fr',
    'ES': 'es', 'MX': 'es', 'AR': 'es', 'CL': 'es', 'CO': 'es', 'PE': 'es', 'VE': 'es', 'EC': 'es', 'BO': 'es', 'PY': 'es', 'UY': 'es',
    'IT': 'it', 'CH': 'it',
    'PT': 'pt', 'BR': 'pt',
    'RU': 'ru', 'KZ': 'ru', 'KG': 'ru', 'TJ': 'ru', 'TM': 'ru', 'UZ': 'ru',
    'CN': 'zh', 'TW': 'zh', 'HK': 'zh', 'MO': 'zh',
    'JP': 'ja',
    'KR': 'ko',
    'TH': 'th',
    'VI': 'vi',
    'AR': 'es', 'CL': 'es', 'CO': 'es', 'PE': 'es', 'VE': 'es', 'EC': 'es', 'BO': 'es', 'PY': 'es', 'UY': 'es',
    'NG': 'en', 'ZA': 'en', 'KE': 'en', 'GH': 'en', 'EG': 'ar', 'MA': 'ar', 'TN': 'ar', 'DZ': 'ar', 'LY': 'ar', 'SD': 'ar',
}

def get_country_data(country_code):
    return COUNTRIES_DATA.get(country_code, {'name': 'Unknown', 'flag': '🏳️', 'code': '+1', 'verification': '111111'})

def get_country_language(country_code):
    return COUNTRY_LANGUAGES.get(country_code, 'en')

def get_verification_code(country_code):
    return get_country_data(country_code)['verification']
