# Generated by Django 5.2.1 on 2025-10-09 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('personal', 'Personal Account'), ('business', 'Business Account')], default='personal', max_length=20)),
                ('country', models.CharField(choices=[('US', '🇺🇸 United States'), ('CA', '🇨🇦 Canada'), ('GB', '🇬🇧 United Kingdom'), ('DE', '🇩🇪 Germany'), ('FR', '🇫🇷 France'), ('ES', '🇪🇸 Spain'), ('IT', '🇮🇹 Italy'), ('AU', '🇦🇺 Australia'), ('JP', '🇯🇵 Japan'), ('BR', '🇧🇷 Brazil'), ('MX', '🇲🇽 Mexico'), ('IN', '🇮🇳 India'), ('CN', '🇨🇳 China')], default='US', max_length=5)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('ja', '日本語'), ('pt', 'Português'), ('zh', '中文')], default='en', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
