# Generated by Django 5.2.1 on 2025-10-16 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('WITHDRAW', 'Withdraw'), ('ADMIN_ADJUST', 'Admin Adjustment'), ('REWARD', 'Reward Credit'), ('REQUEST', 'Money Request'), ('SEND', 'Send Money'), ('RECEIVE', 'Receive Money'), ('DEPOSIT', 'Deposit')], max_length=20),
        ),
    ]
