# Generated by Django 5.2.1 on 2025-10-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='international_fee_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='international_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='international_fee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
