# Generated by Django 5.2.1 on 2025-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_international_fee_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voucher_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
