# Generated by Django 5.2.1 on 2025-10-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_voucher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_notes', to='transactions.transaction')),
            ],
        ),
    ]
