# Generated by Django 5.2.1 on 2025-10-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactionfeenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
