# Generated by Django 5.2.1 on 2025-10-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('frequency', models.CharField(choices=[('ONCE', 'One-time only'), ('DAILY', 'Once per day'), ('UNLIMITED', 'Unlimited')], default='ONCE', max_length=16)),
                ('claimable', models.BooleanField(default=True, help_text='If false, awarded programmatically (e.g., referral)')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rewards.rewardactivitytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
