# Generated by Django 5.2.1 on 2025-10-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewardactivitytype_rewardactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardconversionsettings',
            name='fee_per_block',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardconversionsettings',
            name='payout_per_block',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardconversionsettings',
            name='points_per_block',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
