# Generated by Django 5.2.1 on 2025-10-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewardconversionsettings_fee_per_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtransaction',
            name='blocks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='payout_account',
            field=models.CharField(blank=True, help_text='Destination account/email for payout if applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='receipt_reference',
            field=models.CharField(blank=True, help_text='Reference the user paid fee with (screenshot/ref)', max_length=255),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='COMPLETED', max_length=16),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monetary amount for conversion or activation', max_digits=12),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='points',
            field=models.IntegerField(default=0, help_text='Points involved (use positive value for requested conversion)'),
        ),
    ]
