# Generated by Django 5.2.1 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardtransaction_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardconversionsettings',
            name='payout_account_number',
            field=models.CharField(blank=True, help_text='Account number/name to receive conversion fees', max_length=255),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_receipts/'),
        ),
    ]
