# Generated by Django 5.2.1 on 2025-10-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedcard',
            name='security_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='linkedcard',
            name='card_type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Mastercard', 'Mastercard'), ('Amex', 'Amex'), ('Debit', 'Debit'), ('Saving', 'Saving'), ('Verve', 'Verve')], max_length=20),
        ),
    ]
