# Generated by Django 5.2.1 on 2025-11-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_linkedcard_security_code_alter_linkedcard_card_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='paypal_balance',
            new_name='icici_balance',
        ),
    ]
